# 网站地址（部署前修改）
baseurl = "https://你的域名/"
locale = "zh-cn"

# 网站标题
title = "欢迎来到老宫的博客"

# 网站默认语言
defaultContentLanguage = "zh-cn"

# 中文一定要开启
hasCJKLanguage = true

# 如果不用 Disqus，留空即可
disqusShortname = ""

[pagination]
    pagerSize = 5